### ISSUE TITLE
$Failed error in Mathematica 13.3.0.0

### ISSUE THREAD

**Issue by ianww** [bernie-wu/BernDirac#5]
I'm using Mathematica 13.3.0.0.  

I've downloaded the wl file to `C:\Users\ianww\Documents\Mathematica\BernDirac.wl
`

I run:

```
ClearAll["Global`*"]
Get["C:\\Users\\ianww\\Documents\\Mathematica\\BernDirac.wl"]
```

I try (using esc ket esc to create the ket operator):

![image](https://github.com/bernwo/BernDirac/assets/36909839/c68db757-6c21-498b-a69c-6279df216765)

but I get a failed error:

`$Failed`

I also get the error if I comment out `//MatrixForm`:

![image](https://github.com/bernwo/BernDirac/assets/36909839/286565cb-ae87-4503-9fda-de01c772aa0d)
`$Failed`

I get the same error if I try to run your example file.

I've also tried using `Import `rather than `Get`:

`Import["C:\\Users\\ianww\\Documents\\Mathematica\\BernDirac.wl", "Rules"]`

and it shows the file is loading ok because I get a comprehensive list of rules.  However, the same `$Failed` error occurs.

Do you know if your wl is compatible with Mathematica 13.3.0.0?  Or could there be some other cause that I've missed?

**Comment by bernwo** [comment]
It seems to me that `Bra` and `Ket` has been updated in version 13.3 and thus broke this library. I will fix this and let you know.

**Comment by ianww** [comment]
Thanks!

**Comment by bernwo** [comment]
@ianww I pushed a fix to [`dev`](https://github.com/bernwo/BernDirac/tree/dev) branch. Could you try the fix and see if it works? If so, I will merge the fix with the main branch.

**Comment by ianww** [comment]
Mostly working fine now, thanks, but a couple of things when working through your examples notebook - 

I get a `Symbol Global is protected error` (for +, - and Sn) with `ClearAll["Global'*"]`.  That might just be something my end though - I'm not sure what to do about it.

The DiracForm[] examples generates this output:

![image](https://github.com/bernwo/BernDirac/assets/36909839/9bc3345e-59bf-4e59-845a-3ec4588aac8d)

instead of 

![image](https://github.com/bernwo/BernDirac/assets/36909839/040022b9-9dee-4feb-8af3-ff6c9a046c87)

Similarly, PartialTr[] generates this output:

![image](https://github.com/bernwo/BernDirac/assets/36909839/1d7fedf6-0e01-440c-be80-a960ba7b3729)

instead of:

![image](https://github.com/bernwo/BernDirac/assets/36909839/eead0f88-ca29-4810-b001-e0249434bde5)

**Comment by bernwo** [comment]
Thanks for testing and bringing this other issue to my attention. I found the root cause and fixing it now.

**Comment by bernwo** [comment]
@ianww Can you test again on [`dev`](https://github.com/bernwo/BernDirac/tree/dev) branch for `DiracForm[]`? It should be fixed now.

**Comment by ianww** [comment]
All working ok apart from `PartialTr[]`, which is still showing:

![image](https://github.com/bernwo/BernDirac/assets/36909839/dc7f8875-a4d3-4405-a92f-67aa730fa2d7)
